In [1]:
import numpy as np

# Make random 1D numpy array
a = np.random.rand(5)
print(a)

[ 0.3302401   0.82472352  0.57807805  0.1775024   0.72527737]


In [2]:
# Print the shape of numpy array
print(a.shape)

(5,)


In [3]:
# Dot product of 1D array
b = np.dot(a,a)
print(b)

1.68093600436


In [4]:
# Transpose a numpy array
c = a.T
print(c)
print("Nothing happens eh? There's no transpose for 1D! 1D numpy array is always represetented as row vector")

[ 0.3302401   0.82472352  0.57807805  0.1775024   0.72527737]
Nothing happens eh? Transpose doesn't work for 1D!


In [5]:
# Make a numpy array with shape (3,2) -> 3 row 2 columns
d = np.random.rand(3,2)
print(d)

[[ 0.19176363  0.23078602]
 [ 0.11612489  0.49110749]
 [ 0.19700501  0.08965571]]


In [6]:
# Multiply an 3x2 array by 2x3 array -> 3x3 array
e = np.dot(d, d.T)
print(e)

[[ 0.09003548  0.13560927  0.05846968]
 [ 0.13560927  0.25467156  0.06690778]
 [ 0.05846968  0.06690778  0.04684912]]


In [7]:
# Reshape array e to 9x1 array 
f = e.reshape(9,1)
print(f)

[[ 0.09003548]
 [ 0.13560927]
 [ 0.05846968]
 [ 0.13560927]
 [ 0.25467156]
 [ 0.06690778]
 [ 0.05846968]
 [ 0.06690778]
 [ 0.04684912]]
